### ISSUE TITLE
filter not working

### ISSUE THREAD

**Issue by dmashal** [Icehunter/ffxivapp-plugin-radar#20]
Not sure if this is a new bug as I haven't used APP in a bit.

 Here is a screen shot showing:
http://i.imgur.com/hZVh3Xw.jpg

**Comment by Icehunter** [comment]
There's another setting inside radar->settings->enable.

I have to update the program for 2.5 changes but once complete that should fix it for you.

**Comment by Icehunter** [comment]
It was recently updated for 2.5 does it work okay for you now?

**Comment by Icehunter** [comment]
Fixed in previous build.
