### ISSUE TITLE
Ranked Monsters

### ISSUE THREAD

**Issue by sranger** [Icehunter/ffxivapp-plugin-radar#23]
Awesome to see setting to show ranked monsters (instead of having to have them in the filter list manually); any way we can have an "always show ranked, ignore filter settings" setting?

Also, I had Albin the Ashen for my weekly hunt and he didn't come up as ranked though Flame Sergeant Dalvag did for last weeks (literally 10 mins prior I killed him) so I know it's semi-working.

**Comment by Icehunter** [comment]
Does it appear correctly there?

https://github.com/Icehunter/ffxivapp-plugin-radar/blob/master/FFXIVAPP.Plugin.Radar/Localization/English.cs

Also did you have that rank turned on? :)

**Comment by sranger** [comment]
Yeah, it's correct in the source and I had filters off, only show ranked monsters on, and it literally worked 10 minutes prior on First Sergeant Dalvag. I'll check to make sure I have the most up to date plugin.

Also, how do you enable/disable specific ranks? I only see the toggle for ranked only and the color settings.

**Comment by Icehunter** [comment]
There's an option in monsters to show only the ranked ones already. I had merged in the changes from another user so I will double check any logic in there for it.

**Comment by sranger** [comment]
The app says I have the most current version. Also, with the colors set for the ranks, Albin was colored like a normal mob so that logic wasn't quite right. If I get a chance I'll look at it, too.

**Comment by Icehunter** [comment]
I'm going to be updating the code ASAP to use a different method of resolving the names using case insensitivity. The merge request didn't use those at the time.

Sorry for the late reply, had chicken pox and was out for a couple of weeks :(

**Comment by sranger** [comment]
No problem. I was gonna post about the case sensitive issue today as I ran
into U'Ghamaro mobs using a lower case g on the map so the actual spelling
didn't match

Thanks for the work; hope you're feeling better.

Stephen

**Comment by cybaersam** [comment]
i was the one responsible for the wrong methods i think... ^_^'''
as i've found out that its not working correctly with other languages...
i've reworked the code and tested it with all the ranked monsters i found and so far everything worked
though the only languages i had tested it with was english and german
i don't have the names for any other language
i hope i didn't miss anything  major as everything worked find on my pc...

i've made a pull request for the new code...
so i think once Icehunter has gone through it, it should be ready for everyone to test

as for the case sensitive problem... hmm... why didn't i think of this before i made the pull request...
if we convert the name to lower or upper case when checking then we wouldn't have any problems in that regard anymore...

**Comment by Icehunter** [comment]
Fixed in previous build.
