### ISSUE TITLE
Issue with Radar when running in DX11 mode

### ISSUE THREAD

**Issue by ChapSugar** [Icehunter/ffxivapp-plugin-radar#31]
I'm not sure if this is a Radar or general FFXIV app issue, but Radar will not work (it shows the radar but it's not rotating as I move) when using FFXIV under the newly supported DirectX 11 mode. Under DX9 the game uses ffxiv.exe, but under DX11 the game uses ffxiv_dx11.exe, if that helps. Thank you.

**Comment by Icehunter** [comment]
DX11 isn't supported yet but I'm working on it. Changing the exe won't help as memory is not stored in the same fashion or the same size.

**Comment by Icehunter** [comment]
DX11 is working but on a test build. You can try it out just don't overwrite your folder. Once it's complete I will be pushing it up.

https://github.com/Icehunter/ffxivapp/pull/66

It will require a brand new build using "AnyCPU" rather than x86 when it gets released :)

**Comment by Icehunter** [comment]
Fixed in previous build.
