### ISSUE TITLE
Issue w/ latest version (3.0.5665.32420)

### ISSUE THREAD

**Issue by ChapSugar** [Icehunter/ffxivapp-plugin-radar#34]
Super appreciate your work on this plugin! Thank you!

Seems like the latest release may possibly have introduced an issue as some hunts are not being "identified" as they should be, e.g.: Nahn and Thextera would be two examples.

**Comment by Icehunter** [comment]
So far it seems that it can catch 99.9% of most mobs based on latest testing however there is always sometimes a monster which won't show.

All plugins get the data from the main app and I know for a fact that the memory is sometimes missing a monster. There was a suggestion recently to combine to memory scans into one and just remove duplicates and that is something I will have to consider if I can't determine why this is happening.

The default way the radar works now though is ranked mobs (regardless of filter) are always displayed and the "on options" for them is just to make the font bigger and a different colour.

I'll have to delve into this more.

**Comment by ChapSugar** [comment]
OK. Sounds good. Super appreciate your efforts! Please let us know if we can be of help in any way.

**Comment by Icehunter** [comment]
Please try the latest main application update. Radar won't require an update for this :) Let me know if that fixes it.

**Comment by ChapSugar** [comment]
Working as expected now. Thanks so much!
