### ISSUE TITLE
maybe it can't work in 3.25?

### ISSUE THREAD

**Issue by semi-xi** [Icehunter/ffxivapp-plugin-radar#41]
the plugin is so greate！but it seems not working in the ff14 version 3.25.
i download the newest ff14-app and the plugin-radar ,but it not working?
and i choose the plugin language japan or other language,it alseo can't work?
are you going to update? or just my problem

**Comment by Icehunter** [comment]
I'm working on getting everything updated again; finally got my PC reinstalled and so I can start working on memlocs.

I can push out a new version that will work with directx9 tonight; but directx11 will have to wait a few days until I ensure everything is working as intended.

**Comment by semi-xi** [comment]
@Icehunter so tonight i try again with dx9 。 before that i need to download the newest again。i wait for the test tonight~
